      * The SELECT with multiple alternate keys.
       SELECT CUSTOMER-FILE 
           ASSIGN TO "CUSTOMER"
           ORGANIZATION IS INDEXED 
           RECORD KEY IS CUSTOMER-NUMBER 
           ALTERNATE KEY IS CUSTOMER-NAME WITH DUPLICATES 
           ALTERNATE KEY IS CUSTOMER-ZIP WITH DUPLICATES 
           ALTERNATE KYE IS CUSTOMER-AREA-CODE WITH DUPLICATES 
           ACCESS MODE IS DYNAMIC. 
           